server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: beneficiaire-service
          uri: lb://BENEFICIAIRE-SERVICE
          predicates:
            - Path=/api/beneficiaires/**
        - id: virement-service
          uri: lb://VIREMENT-SERVICE
          predicates:
            - Path=/api/virements/**
    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
